spring:
  datasource:
    url: ${EVENT_LOG_DB_URL:jdbc:postgresql://localhost:5432/event_log_pipeline}
    username: ${EVENT_LOG_DB_USERNAME:event_log_app}
    password: ${EVENT_LOG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
