apiVersion: v1
kind: ConfigMap
metadata:
  name: event-generator-config
data:
  SPRING_PROFILES_ACTIVE: db
  EVENT_LOG_DB_URL: jdbc:postgresql://event-log-postgres.example.internal:5432/event_log_pipeline
  EVENT_GENERATOR_SESSION_COUNT: "5000"
  EVENT_GENERATOR_HEARTBEAT_INTERVAL_MINUTES: "5"
